### PR TITLE
Logging, autodetection, and some metafiles.

### PR DESCRIPTION
**Pull request by abl**
See each comment's long description for the individual details - the callouts here are autodetection of Pebble ID, logging based on the Python logging module, and a little work to make libpebble easier to use as a submodule.

The logging change is probably the most controversial - I needed them to debug issues with my Air's bluetooth (and my attempts to repack a tweaked watchface :) and thought it might be a good start / useful for others.

### CODE REVIEW

**Comment by abl** [comment]
Canceling this due to test failure - bad cherrypick on my part, apologies.

**Comment by Hexxeh** [comment]
Looks like a good change, been meaning to go fix up all the exceptions... :)

**Comment by abl** [comment]
Yeah...something is causing it to no longer pair to my Pebble post-changes. Probably unrelated but, you know... :)

**Comment by abl** [comment]
Looks like it was an issue with my pairing - false alarm...should be good to pull.

**Pull request merged**
